build:
  image: "rust:latest"
  variables:
    CARGO_HOME: "cargohome"
  cache:
    paths:
      - target
      - cargohome
    key: build_cache
  before_script:
    - mkdir -p $CARGO_HOME && echo "using $CARGO_HOME to cache cargo deps"
    - cargo install cargo-tarpaulin  
  script:
    - rustc --version && cargo --version      # Print version info for debugging
    - cargo tarpaulin --all-features --out Lcov
    - bash <(curl -s https://codecov.io/bash) -Z
  only:
    changes:
      - Cargo.toml
      - ./*/Cargo.toml
      - structsy/**/*
      - structsy-derive/**/*
      - benches/**/*
      - examples/**/*

