[package]
name = "structsy"
version = "0.1.0"
authors = ["Tglman <tglman@tglman.com>"]
edition = "2018"

[dependencies]
persy = { git = "https://gitlab.com/tglman/persy.git"}
byteorder="1.3"


[dev-dependencies]
structsy-derive= { path="structsy-derive"}
tempfile="3.0"
