[package]
name = "structsy_tools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
persy_expimp = {git="https://gitlab.com/tglman/persy_expimp.git", branch="master"}
