[package]
name = "actix_web"
version = "0.1.0"
authors = ["Tglman <tglman@tglman.com>"]
edition = "2018"

[dependencies]
actix-web="3.0"
actix-rt = "1.0"
structsy = "0.3"
structsy-derive = "0.3"
serde ="1.0"
serde_derive="1.0"
