[package]
name = "actix_web"
version = "0.1.0"
authors = ["Tglman <tglman@tglman.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3"
actix-rt = "1.1"
structsy = {path="../../structsy"}
structsy-derive = {path="../../structsy-derive"}
serde ="1.0"
serde_derive="1.0"
